export APP_NAME='example-app-name'
export WEBSITE_DOMAIN_NAME=''
export RESTAPI_DOMAIN_NAME="api.$WEBSITE_DOMAIN_NAME"
export HOSTEDZONE_ID=''
export SSL_CERTIFICATE_ARN=''
export REPOSITORY_NAME=''
export DB_SNAPSHOT_NAME=''